# 2. Operações Aritméticas Simples
print("===Calculadora Simples===\n")
n1 = float(input('Digite um número: '))
n2 = float(input('Digite um número: '))
print("\n===================\n    RESULTADOS\n===================")
print(str(n1)+" + "+str(n2)+" = "+str(format((n1 + n2), '.1f')))
print(str(n1)+" - "+str(n2)+" = "+str(format((n1 - n2), '.1f')))
print(str(n1)+" * "+str(n2)+" = "+str(format((n1 * n2), '.1f')))
print(str(n1)+" / "+str(n2)+" = "+str(format((n1 / n2), '.1f')))
print("===================")